### numpy-> play with array(numbers)
### pandas -> datasets
### matplotible -> Data visulization
### seaborn -> Data visualization
### Scipy ->Statical
### sklearn-> Algorithem

### numpy:package for multidimensional array

In [1]:
import numpy as np

In [2]:
simple_list=[1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_list=np.array([[12,34,5],[3,5,6],[67,5,2]])
list_of_list

array([[12, 34,  5],
       [ 3,  5,  6],
       [67,  5,  2]])

In [7]:
np.arange(4,21)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
np.arange(2,200)

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

In [10]:
np.arange(1,24,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.ones((2,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,3,6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

In [20]:
np.linspace(2,40,8)

array([ 2.        ,  7.42857143, 12.85714286, 18.28571429, 23.71428571,
       29.14285714, 34.57142857, 40.        ])

In [22]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [23]:
np.random.rand(2,4)

array([[0.03661243, 0.74914703, 0.43114396, 0.97301012],
       [0.14957847, 0.648606  , 0.76994069, 0.26956343]])

In [26]:
arr=np.random.randn(2,3)
arr

array([[-1.50255367, -0.05527575, -0.07190707],
       [ 0.11814815, -0.39317675, -0.48890987]])

In [27]:
np.random.randint(3,50)

22

In [32]:
rand_array=np.random.randint(2,50,100)

In [29]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [33]:
rand_array.max()

49

In [34]:
rand_array.argmax()

75

In [38]:
a=np.eye(5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [39]:
a.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [40]:
a=np.random.rand(2,3)

In [41]:
a.T

array([[0.62563637, 0.20161122],
       [0.14703404, 0.04374018],
       [0.66305991, 0.71028331]])

In [42]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
sample_array[2:5]

array([12, 13, 14])

In [44]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [45]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [46]:
subset_array=sample_array[0:7]

In [48]:
subset_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [49]:
subset_array[:]=1001
subset_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two Dimensional Array

In [1]:
import numpy as np

In [10]:
sample_matrix=np.array([[40,34,56,3],[2,54,1,6],[41,98,3,8]])
sample_matrix

array([[40, 34, 56,  3],
       [ 2, 54,  1,  6],
       [41, 98,  3,  8]])

In [11]:
sample_matrix[1,2]

1

In [12]:
sample_matrix[1,:]
sample_matrix[:,2]

array([56,  1,  3])

In [13]:
sample_matrix[:,(1,2)]

array([[34, 56],
       [54,  1],
       [98,  3]])

In [15]:
sample_matrix[1,(1,2)]

array([54,  1])

### selction techniques

In [17]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [19]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.sqrt(sample_array)

In [ ]:
np.log(sample_array)

In [ ]:
np.max(sample_array)

In [ ]:
np.min(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.argmin(sample_array)

In [ ]:
np.square(sample_array)

In [ ]:
np.std(sample_array)

In [ ]:
np.var(sample_array)

In [ ]:
np.mean(sample_array)

In [24]:
array=np.random.randn(3,4)
array

array([[-0.4096619 , -0.27811557,  0.63185026,  0.85610924],
       [ 0.15795014, -0.84908783,  0.67283299, -0.52128066],
       [ 1.08315401,  0.99765257, -0.33012393,  0.53014132]])

In [26]:
np.round(array,decimals=2)

array([[-0.41, -0.28,  0.63,  0.86],
       [ 0.16, -0.85,  0.67, -0.52],
       [ 1.08,  1.  , -0.33,  0.53]])

In [27]:
sports=np.array(['golf','cricket','fball','cricket'])
sports

array(['golf', 'cricket', 'fball', 'cricket'], dtype='<U7')

In [28]:
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

### pandas dataframe and indexing

In [34]:
import pandas as pd
import numpy as np

In [36]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [38]:
sports1['football']

2

In [39]:
sports2=pd.Series([11,2,3,5],index=['cricket','baseball','basketball','tennis'])
sports2

cricket       11
baseball       2
basketball     3
tennis         5
dtype: int64

In [40]:
sports1+sports2

baseball       NaN
basketball     6.0
cricket       12.0
football       NaN
golf           NaN
tennis         NaN
dtype: float64

In [42]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.859609  0.087058  0.737149  0.000249  0.169268
B  0.385628  0.675717  0.063391  0.856847  0.036862
C  0.953319  0.913568  0.102512  0.093955  0.917138
D  0.816083  0.697668  0.250956  0.028686  0.211772
E  0.385671  0.599114  0.542850  0.842349  0.435613
F  0.120832  0.331510  0.811765  0.954875  0.494569
G  0.148019  0.287373  0.963762  0.262107  0.097509
H  0.910050  0.909291  0.349741  0.044165  0.239798

In [45]:
df1[["score1"]]

score1
A  0.859609
B  0.385628
C  0.953319
D  0.816083
E  0.385671
F  0.120832
G  0.148019
H  0.910050

In [46]:
df1[["score1","score2"]]

score1    score2
A  0.859609  0.087058
B  0.385628  0.675717
C  0.953319  0.913568
D  0.816083  0.697668
E  0.385671  0.599114
F  0.120832  0.331510
G  0.148019  0.287373
H  0.910050  0.909291

In [49]:
df1['score6']=df1['score1']+df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.859609  0.087058  0.737149  0.000249  0.169268  0.946667
B  0.385628  0.675717  0.063391  0.856847  0.036862  1.061345
C  0.953319  0.913568  0.102512  0.093955  0.917138  1.866887
D  0.816083  0.697668  0.250956  0.028686  0.211772  1.513751
E  0.385671  0.599114  0.542850  0.842349  0.435613  0.984784
F  0.120832  0.331510  0.811765  0.954875  0.494569  0.452342
G  0.148019  0.287373  0.963762  0.262107  0.097509  0.435392
H  0.910050  0.909291  0.349741  0.044165  0.239798  1.819341

In [53]:
df2={'ID':['101','102','103','104','105'],'Name':['johny','mercy','Akash','vivek','gitika'],'profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID    Name  profit
0  101   johny      20
1  102   mercy      54
2  103   Akash      56
3  104   vivek      87
4  105  gitika     123

In [54]:
df[['ID']]

ID
0  101
1  102
2  103
3  104
4  105

In [55]:
df[['ID','Name']]

ID    Name
0  101   johny
1  102   mercy
2  103   Akash
3  104   vivek
4  105  gitika